### ISSUE TITLE
Error message on load.

### ISSUE THREAD

**Issue by GlowingBear0696** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves#10]
"Exception from asynchronous event: System.MissingMethodException: Method not found: 'Verse.Log.Error'.
  at Verse.LongEventHandler.RunEventFromAnotherThread (System.Action action) [0x00000] in <filename unknown>:0 "

EDIT: Part of the error above gets lost in the preview, sorry I don't know how to keep it from doing that.

The above error message (in "RED") occurs with the listed below version of the game and mods, in load order below.

RimWorld 0.19.2009 (Mac)

Core
HugsLib (v5.0.2)
JecsTools (1.1.07)
Humanoid Alien Races 2.0
Doors Expanded (1.19.0.4)
Lord of the Rims - Unlimited (v0.8.6)
Lord of the Rims - Elves (1.19.0.2)

If I take away the Elves mod the error goes away. I'm including the log file itself and a screenshot of the error.

[output_log.txt](https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves/files/2489468/output_log.txt)
![screen shot 2018-10-17 at 6 03 45 pm](https://user-images.githubusercontent.com/44231865/47119333-7c499a00-d238-11e8-8646-0610b25a6b4d.png)

**Comment by jecrell** [comment]
Fixed previously.
