### ISSUE TITLE
Backstory translation does not work properly.

### ISSUE THREAD

**Issue by Proxyer** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves#5]
This is a problem of "Humanoid Alien Races 2.0" mod side, so it seems that there is no solution only to create a patch separately.

Although attempting various means, the Japanese translation backstory did not apply unless directly change the description in "/Defs/BackstoryDef/LotRE_ElfBackstories.xml".

Therefore, I think that it is necessary to create Sub-Mod (for patch only) for Japanese translation separately from this Mod.

**Comment by Proxyer** [comment]
For now, I responded by creating a patch and publishing it as Sub-MOD. If another solution is found, we will stop publishing Sub-Mod.

**Comment by jecrell** [comment]
@Proxyer Was this issue addressed?

**Comment by Proxyer** [comment]
As for this problem, it will be reflected well at 1.0 version.
