### ISSUE TITLE
Salted Meat Doubling

### ISSUE THREAD

**Issue by desgath** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---Elves#8]
Relatively minor issue I encountered with some annoying consequences. Both the Third Age mod and Unlimited seem affected, verified independently of each other, not both at the same time, obviously.

What happens is that for each type of meat there seem to be two identical instances of salted meat which do not stack with one another, requiring more storage space and work by pawns, etc. Also, this seems to lead to a doubling of the number of resources shown in the rescource tracker in the upper left corner, meaning that for 1 salted meat in storage, the tracker displays 2.

How to reproduce: Start new colony with Third Age or Unlimited active, designate a stockpile zone and in the storage tab navigate to
Foods > Raw Food > Meat > Salted Meat
There you should see that every type of salted meat is listed twice.

HugsLog: https://gist.github.com/HugsLibRecordKeeper/5eced91a33667db8aa727aff0abe0ba7

All mods are up to date Steam versions as of 23 Sep 2018.

**Comment by jecrell** [comment]
Moved to appropriate place.
https://github.com/Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---The-Third-Age/issues/23
